import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  ImageRun,
  LevelFormat,
  Packer,
  PageNumber,
  Paragraph,
  type Table,
  TabStopPosition,
  TabStopType,
  TextRun,
} from "docx"
import type { TemplateTokens } from "./types"

export async function buildDocument(
  body: (Paragraph | Table)[],
  t: TemplateTokens,
  logoData: ArrayBuffer | null
): Promise<Uint8Array> {
  const headerChildren: Paragraph[] = []

  if (logoData) {
    headerChildren.push(
      new Paragraph({
        alignment: AlignmentType.RIGHT,
        spacing: { after: 0 },
        children: [
          new ImageRun({
            type: "png",
            data: new Uint8Array(logoData),
            transformation: { width: 152, height: 71 },
            altText: {
              title: "Logo",
              description: "Document logo",
              name: "logo",
            },
          }),
        ],
      })
    )
  }
  headerChildren.push(
    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: "Generated by dox",
          font: t.fonts.major,
          size: 18,
          color: t.colors.text1Tint80,
        }),
      ],
    })
  )

  const doc = new Document({
    styles: {
      default: {
        document: { run: { font: t.fonts.minor, size: t.defaults.fontSize } },
      },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 36, font: t.fonts.major, allCaps: true },
          paragraph: {
            spacing: { before: 400, after: 40 },
            keepNext: true,
            keepLines: true,
            outlineLevel: 0,
          },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 28, font: t.fonts.major, allCaps: true },
          paragraph: {
            spacing: { before: 120, after: 0 },
            keepNext: true,
            keepLines: true,
            outlineLevel: 1,
          },
        },
        {
          id: "Heading3",
          name: "Heading 3",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 28, font: t.fonts.major, smallCaps: true },
          paragraph: {
            spacing: { before: 120, after: 0 },
            keepNext: true,
            keepLines: true,
            outlineLevel: 2,
          },
        },
      ],
    },
    numbering: {
      config: [
        {
          reference: "bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "\u25CF",
              alignment: AlignmentType.LEFT,
              style: {
                paragraph: { indent: { left: 720, hanging: 360 } },
                run: { font: t.fonts.bulletFont, size: t.defaults.fontSize },
              },
            },
            {
              level: 1,
              format: LevelFormat.BULLET,
              text: "\u25CB",
              alignment: AlignmentType.LEFT,
              style: {
                paragraph: { indent: { left: 1440, hanging: 360 } },
                run: { font: t.fonts.bulletFont, size: t.defaults.fontSize },
              },
            },
          ],
        },
        {
          reference: "numbers",
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: "%1.",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: t.page.width, height: t.page.height },
            margin: t.page.margin,
          },
          titlePage: false,
        },
        headers: { default: new Header({ children: headerChildren }) },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                border: {
                  left: {
                    style: BorderStyle.SINGLE,
                    size: 12,
                    space: 11,
                    color: t.colors.accent1,
                  },
                },
                tabStops: [
                  { type: TabStopType.RIGHT, position: TabStopPosition.MAX },
                ],
                children: [
                  new TextRun({
                    font: t.fonts.major,
                    size: 26,
                    color: t.colors.accent1ShadeBF,
                    children: [PageNumber.CURRENT],
                  }),
                  new TextRun({
                    font: t.fonts.major,
                    size: 26,
                    color: t.colors.accent1ShadeBF,
                    children: ["\tdox"],
                  }),
                ],
              }),
            ],
          }),
        },
        children: body,
      },
    ],
  })

  const arrayBuffer = await Packer.toArrayBuffer(doc)
  return new Uint8Array(arrayBuffer)
}
